export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const USER_REGISTER = "USER_REGISTER";

export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE";

export const MY_BOOKS_FAILURE = "MY_BOOKS_FAILURE";
export const MY_BOOKS_SUCCESS = "MY_BOOKS_SUCCESS";
export const MY_BOOKS_REQUEST = "MY_BOOKS_REQUEST";

export const ADD_BOOK_REQUEST = "ADD_BOOK_REQUEST";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAILURE = "ADD_BOOK_FAILURE";

export const UPDATE_BOOK_FAILURE = "UPDATE_BOOK_FAILURE";
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";
export const UPDATE_BOOK_REQUEST = "UPDATE_BOOK_REQUEST";
